// Header
export const CHANGE_TEXT = 'CHANGE_TEXT'
export const CLEAR_DATA = 'CLEAR_DATA'

// Books Card
export const BOOKS_DATA_START = 'BOOKS_DATA_START'
export const BOOKS_DATA_SUCCESS = 'BOOKS_DATA_SUCCESS'
export const BOOKS_DATA_FAIL = 'BOOKS_DATA_FAIL'
export const ONE_BOOK_REQUESTED = 'ONE_BOOK_REQUESTED'
export const ALL_BOOKS_REQUESTED = 'ALL_BOOKS_REQUESTED'
